In [1]:
# Torch fonction
import torch

import time

randint = torch.randint(-100,100,(6,))
print(randint)

tensor = torch.tensor([[0.1,0.2],[1.1,3.2],[4.1,2.2]])
print(tensor)

zeros = torch.zeros(3,2)
print(zeros)

ones = torch.ones(4,2)
print(ones)

input = torch.empty(3,2)
print(input)

arrange = torch.arange(5)
print(arrange)

linspace = torch.linspace(3,10, steps=5)
print(linspace)

logspace=torch.logspace(start=-10, end=10, steps=5)
print(logspace)

eye =torch.eye(5)
print(eye)

a=torch.empty((2,3),dtype=torch.int64)
empty_like =torch.empty_like(a)
print(empty_like)

#time
start_time =time.time()
zeros = torch.zeros(1,1)
end_time =time.time()

elapsed = end_time - start_time
print(f"{elapsed:.10f}")

#probabilité
probabilities=torch.tensor([0.1,0.9])
samples=torch.multinomial(probabilities,num_samples=10,replacement=True)
print(samples)

#combiner plusieurs tensor
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])),dim=0)
print(out)

out1 = torch.tril(torch.ones(5,5))
print(out1)

out1 = torch.triu(torch.ones(5,5))
print(out1)

#transpose
input = torch.zeros([2,3,4])
out=input.transpose(0,2)
print(out.shape)

#Stack

input0 = torch.tensor([2,3,4])
input1 = torch.tensor([2,3,4])
input2= torch.tensor([2,3,4])

stacked_tensor=torch.stack([input0,input1,input2])
print(stacked_tensor)

#linear neuronne y=ax+b no b
import torch.nn as nn
sample=torch.tensor([10.,10.,10.])
linear=nn.Linear(3,3,bias=False)
print(linear(sample))

#softmax
import torch.nn.functional as F
tensor1= torch.tensor([1.0,2.0,3.0])
softmax_tensor =F.softmax(tensor1,dim=0)
print(softmax_tensor)



tensor([-77, -56, -61,  85, -16,  -4])
tensor([[0.1000, 0.2000],
        [1.1000, 3.2000],
        [4.1000, 2.2000]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[-9.9390e-32,  1.1967e-42],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])
tensor([0, 1, 2, 3, 4])
tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])
tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[0, 0, 0],
        [0, 0, 0]])
0.0000000000
tensor([1, 1, 0, 0, 1, 1, 1, 1, 1, 1])
tensor([1, 2, 3, 4, 5])
tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 

In [2]:
#embedding
import torch.nn as nn

vocab_size =1000
embedding_dim =100
embedding=nn.Embedding(vocab_size,embedding_dim)

intput =torch.LongTensor([1,2,3,4])

embedded_output=embedding(intput)

print(embedded_output.shape)



torch.Size([4, 100])


In [3]:
#multiplier des matrices (3,2) -> (2,3)
a=torch.tensor([(1,2),(2,4),(5,3)])
b=torch.tensor([(3,4,5),(6,4,9)])
print(a.shape)
print(b.shape)
print(a@b)

torch.Size([3, 2])
torch.Size([2, 3])
tensor([[15, 12, 23],
        [30, 24, 46],
        [33, 32, 52]])


In [4]:
int_64=torch.randint(1,(3,2)).float()
float_32=torch.rand(2,3)
print(int_64.shape)
print(float_32.shape)
print(int_64)
print(float_32)

result=torch.matmul(int_64,float_32)
print(result)

torch.Size([3, 2])
torch.Size([2, 3])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0.8507, 0.0501, 0.9670],
        [0.2686, 0.5247, 0.3316]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
